name: Install NVM, NPM and node

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          cd ${{ github.workspace }}
          echo "[DEBUG] Current directory, contents, env.variables"
          pwd
          ls -al
          env | set

          cd $WORKSPACE
          rm -rf node_modules
          rm -f .env

          echo "-----------Install NVM--------"
          if [ ! -f ~/.nvm/nvm.sh ]; then

            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
          fi
          set +ex
          source ~/.nvm/nvm.sh
          nvm install
          nvm use
          set -ex

          node --version
          npm  --version

          npm install event-stream
          npm install
          npm test

